create TABLE IF NOT EXISTS users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
    email varchar(50) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT unique_user_email UNIQUE (email),
    CONSTRAINT unique_user_name UNIQUE (name)
);

create TABLE IF NOT EXISTS categories (
    category_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT unique_category_name UNIQUE (name)
);

create TABLE IF NOT EXISTS locations (
    location_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude real NOT NULL,
    longitude real NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (location_id)
);

create TABLE IF NOT EXISTS events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation varchar(4000) NOT NULL,
    created timestamp without time zone NOT NULL,
    description varchar(8000) NOT NULL,
    event_date timestamp without time zone NOT NULL,
    paid boolean NOT NULL,
    participant_limit  integer NOT NULL,
    published timestamp without time zone,
    request_moderation boolean NOT NULL,
    state varchar(50) NOT NULL,
    title varchar(100) NOT NULL,
    category_id bigint REFERENCES categories (category_id) ON DELETE RESTRICT,
    initiator_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    location_id bigint REFERENCES locations (location_id) ON DELETE RESTRICT,
    CONSTRAINT pk_event PRIMARY KEY (event_id)
);

create TABLE IF NOT EXISTS comments (
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text varchar(3000) NOT NULL,
    event_id bigint REFERENCES events (event_id) ON DELETE CASCADE,
    author_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    created timestamp without time zone NOT NULL,
    edited timestamp without time zone,
    status varchar(50) NOT NULL
);

create TABLE IF NOT EXISTS requests (
    request_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id bigint REFERENCES events (event_id) ON DELETE CASCADE,
    created timestamp without time zone NOT NULL,
    requester_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    status varchar(50) NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (request_id)
);

create TABLE IF NOT EXISTS compilations (
    compilation_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned boolean NOT NULL,
    title varchar(100) NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (compilation_id)
);

CREATE TABLE IF NOT EXISTS events_compilations (
    events_compilation_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id bigint NOT NULL REFERENCES compilations (compilation_id) ON DELETE CASCADE,
    event_id bigint REFERENCES events (event_id) ON DELETE CASCADE,
    CONSTRAINT pk_events_compilation PRIMARY KEY (events_compilation_id)
);
