CREATE TABLE IF NOT EXISTS stats (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app varchar(100) NOT NULL,
    uri varchar(200) NOT NULL,
    ip varchar(45) NOT NULL,
    timestamp timestamp without time zone NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);